#!/usr/bin/env bash

version="0.0.1"

walldir="$HOME/Downloads"
cachedir="$HOME/.cache/wallhaven"
sxiv_otps=" -tfpo -z 200" # o is needed for selection
max_pages=5
sorting=relevance
quality=large
atleast=1920x1080

[ -e "$HOME/.config/getwallrc" ] && . "$HOME/.config/getwallrc"

sh_menu() {
    : | dmenu -p "search wallhaven:"
}

[ -n "$*" ] && query="$*" || query=$(sh_menu)
[ -z "$query" ] && exit 1
query=$(printf '%s' "$query" | tr ' ' '+')

rm -rf "$cachedir"
mkdir -p "$walldir" "$cachedir"

sh_info() {
    printf "%s\n" "$1" >&2
    notify-send "wallhaven" "$1"
    [ -n "$2" ] && exit "$2"
}

dep_ck() {
    for pr; do
        command -v $pr >/dev/null 2>&1 || sh_info "command $pr not found, install: $pr" 1
    done
}
dep_ck "sxiv" "curl" "jq"

clean_up() {
    printf "%s\n" "cleaning up..." >&2
    rm -rf "$datafile" "$cachedir"
}

datafile="/tmp/wald.$$"

trap "exit" INT TERM
trap "clean_up" EXIT

get_results() {
    for page_no in $(seq $max_pages); do
        {
            json=$(
                curl -s -G "https://wallhaven.cc/api/v1/search" \
                    -d "q=$1" \
                    -d "page=$page_no" \
                    -d "atleast=$atleast" \
                    -d "sorting=$sorting"
            )
            printf "%s\n" "$json" >>"$datafile"
        } &
        sleep 0.001
    done
    wait
}

sh_info "getting data..."
get_results "$query"

[ -s "$datafile" ] || sh_info "no images found" 1

thumbnails=$(jq -r '.data[]?|.thumbs.'"$quality" <"$datafile")
[ -z "$thumbnails" ] && sh_info "no-results found" 1

sh_info "caching thumbnails..."
for url in $thumbnails; do
    printf "url = %s\n" "$url"
    printf "output = %s\n" "$cachedir/${url##*/}"
done | curl -Z -K -

image_ids="$(sxiv $sxiv_otps "$cachedir")"
[ -z "$image_ids" ] && exit

cd "$walldir"
sh_info "downloading wallpapers..."
for ids in $image_ids; do
    ids="${ids##*/}"
    ids="${ids%.*}"
    url=$(jq -r '.data[]?|select( .id == "'$ids'" )|.path' <"$datafile")
    printf "url = %s\n" "$url"
    printf -- "-O\n"
done | curl -K -

sh_info "wallpapers downloaded in:- '$walldir'"
sxiv $(ls -c)
