#!/usr/bin/env bash

mkdir -p $HOME/.cache/notflix

menu="dmenu -i -l 20"
baseurl="https://1337x.to"
cachedir="$HOME/.cache/notflix"

category=$(dmenu -p "Movies? TV? Documentaries? Anime? (1,2,3,4): " <&-)
case $category in
"1") category="Movies" ;;
"2") category="TV" ;;
"3") category="Documentaries" ;;
"4") category="Anime" ;;
*) category="Movies" ;;
esac

if [ -z $1 ]; then
    query=$(dmenu -p "Search Torrent: " <&-)
else
    query=$1
fi
query="$(echo $query | sed 's/ /+/g')"

curl -s "$baseurl/category-search/$query/$category/1/" >"$cachedir/tmp.html"

grep -o '<a href="/torrent/.*</a>' "$cachedir/tmp.html" |
    sed 's/<[^>]*>//g' >"$cachedir/titles.bw"

result_count=$(wc -l "$cachedir/titles.bw" | awk '{print $1}')
if [ "$result_count" -lt 1 ]; then
    notify-send "No Result found. Try again" -i "NONE"
    exit 0
fi

grep -o '<td class="coll-2 seeds.*</td>\|<td class="coll-3 leeches.*</td>' "$cachedir/tmp.html" |
    sed 's/<[^>]*>//g' | sed 'N;s/\n/ /' >"$cachedir/seedleech.bw"

grep -o '<td class="coll-4 size.*</td>' "$cachedir/tmp.html" |
    sed 's/<span class="seeds">.*<\/span>//g' |
    sed -e 's/<[^>]*>//g' >"$cachedir/size.bw"

grep -E '/torrent/' "$cachedir/tmp.html" |
    sed -E 's#.*(/torrent/.*)/">.*#\1#' >"$cachedir/links.bw"

sed 's/\./ /g; s/\-/ /g' "$cachedir/titles.bw" |
    sed 's/[^A-Za-z0-9 ]//g' | tr -s " " >"$cachedir/tmp" && mv "$cachedir/tmp" "$cachedir/titles.bw"

awk '{print NR " - ["$0"]"}' "$cachedir/size.bw" >"$cachedir/tmp" && mv "$cachedir/tmp" "$cachedir/size.bw"
awk '{print "[S:"$1 ", L:"$2"]" }' "$cachedir/seedleech.bw" >"$cachedir/tmp" && mv "$cachedir/tmp" "$cachedir/seedleech.bw"

LINE=$(paste -d\  "$cachedir/size.bw" "$cachedir/seedleech.bw" "$cachedir/titles.bw" |
    $menu |
    cut -d\- -f1 |
    awk '{$1=$1; print}')

if [ -z "$LINE" ]; then
    notify-send "No Result selected. Exiting..." -i "NONE"
    exit 0
fi

notify-send "Searching Magnet seeds" -i "NONE"

url=$(head -n $LINE "$cachedir/links.bw" | tail -n +$LINE)
fullURL="${baseurl}${url}/"
curl -s "$fullURL" >"$cachedir/tmp.html"

magnet=$(grep -Po 'href="magnet:\?xt=urn:btih:[^"]+"' "$cachedir/tmp.html" | head -n 1 | sed 's/href="//;s/"$//')

if [ -z "$magnet" ]; then
    notify-send "Magnet link not found" -i "NONE"
    exit 0
fi

webtorrent "$magnet" --mpv
notify-send "Enjoy Watching" -i "NONE"
