#!/usr/bin/env bash

output="$(date '+%y%m%d-%H%M-%S').png"
xclip_cmd="xclip -sel clip -t image/png"
ocr_cmd="xclip -sel clip"

case "$(printf "Select Area\nFullscreen" | dmenu -l 2)" in
"Select Area") scrot -s pic-selected-"${output}" ;;
"Fullscreen") maim -q -d 0.2 pic-full-"${output}" ;;
esac
